### ISSUE TITLE
Retirer la documentation du dépôt et la déployer sur un site web

### ISSUE THREAD

**Issue by Olon11** [profcfuhrmanets/log210-systeme-gestion-bordereau-node-express-ts#1]
En ce moment, la documentation de l'API du SGB est dans le dossier `dist` du dépôt. C'est une mauvaise pratique, car on peut oublier de la mettre à jour et ça se versionne mal.
Je suggère :

- [x] Supprimer le dossier `dist`
- [x] Ajouter `dist` dans le .gitignore
- [ ] Générer et déployer la documentation à chaque commit avec l'intégration continue et la déployer sur un site web `https://pages.github.com/`

**Comment by Olon11** [comment]
Pour générer la documentation, il faut exécuter `npm run all_docs`

**Comment by Olon11** [comment]
On dirait qu'on ne pourra pas utiliser pages.github.com, car la documentation est interactive. On peut y faire des appels d'API et Pages ne supporte que le contenu statique. Je vais réfléchir à une solution.

**Comment by fuhrmanator** [comment]
Je pense qu'on pourrait avoir les deux. La version sur pages.github.com ne serait pas interactive, mais elle est disponible sans rouler le serveur.

Il faudra trouver un moyen de générer la version qui va sur GitHub Pages. Je sais faire avec `/docs`, mais c'est plus haut que `/dist/docs` qui est normalement servi quand on roule le serveur. Ça serait dommage d'avoir deux copies. Peut-être avec une action GitHub on peut personnaliser le répertoire de source pour la documentation (`/dist/docs`). Je génère la doc avec la version du CI la plus récente afin que le test de la présence de la doc passe: https://github.com/profcfuhrmanets/log210-systeme-gestion-bordereau-node-express-ts/blob/a2fff52a6cb5527fe0ee05b57bfc21df991e0071/.github/workflows/build-and-tests.yml#L23C6-L24C26
