### ISSUE TITLE
Le SGB devrait être un API REST de niveau 2

### ISSUE THREAD

**Issue by Olon11** [profcfuhrmanets/log210-systeme-gestion-bordereau-node-express-ts#11]
On devrait utiliser POST pour ajouter du contenu. Techniquement, GET ne devrait pas modifier l'état du système.

**Comment by fuhrmanator** [comment]
Je suis d'accord en principe. La meilleure issue va spécifier quel(s) service(s) REST.

**Comment by Olon11** [comment]
Il suffit de modifier `/api/v3/grade/insert` pour utiliser POST. Puis, il faudra mettre à jour le README.
