### ISSUE TITLE
Ajouter des tests de mutation

### ISSUE THREAD

**Issue by Olon11** [profcfuhrmanets/log210-systeme-gestion-bordereau-node-express-ts#12]
Je suggère de tester l'ajout de tests de mutation. Cela permettra d'assurer la qualité des tests du SGB et si tout fonctionne bien, on pourrait intégrer la mesure au projet de session.

Ma suggestion : https://github.com/stryker-mutator/stryker-js

**Comment by fuhrmanator** [comment]
Pas une priorité pour l'instant.
