### ISSUE TITLE
Est-ce qu'on a vraiment besoin de Docker?

### ISSUE THREAD

**Issue by Olon11** [profcfuhrmanets/log210-systeme-gestion-bordereau-node-express-ts#13]
Ça ajoute une complexité supplémentaire pour les étudiants. Le SGB devrait être installé de la même manière que le squelette pour simplifier la tâche aux étudiants.

- [x] Supprimer `.dockerignore`
- [x] Supprimer `Dockerfile`
- [x] Supprimer la commande NPM `start-docker`
- [x] Éditer le README

**Comment by fuhrmanator** [comment]
Je suis d'accord avec toi. Il faudra demander dans le discord (anciens chargés) pour savoir -- peut-être c'est utilisé pour corriger automatiquement?

**Comment by Olon11** [comment]
Pour l'instant, j'ai écrit dans 4dcf5cb que c'est optionnel.

**Comment by Olon11** [comment]
En regardant l'historique des fichiers Docker, je vois qu'ils ont été créés par un ancien étudiant. Probablement qu'il préférait exécuter le SGB de cette façon. Je comprends donc que ce n'est pas essentiel et qu'on peut les supprimer. Aucun chargé de laboratoire n'a indiqué utiliser Docker pour corriger.

Aussi, je ne suis pas certain que ça fonctionne encore avec tous les changements qu'on a fait.

**Comment by fuhrmanator** [comment]
Ok, on supprime
