### ISSUE TITLE
Mettre à jour les dépendances dans package.json

### ISSUE THREAD

**Issue by Olon11** [profcfuhrmanets/log210-systeme-gestion-bordereau-node-express-ts#15]
Cela fait trois ans qu'il n'y a pas eu de mise à jour.

**Comment by fuhrmanator** [comment]
Vérifie la branche https://github.com/profcfuhrmanets/log210-systeme-gestion-bordereau-node-express-ts/tree/nochai-migration

**Comment by Olon11** [comment]
J'ai du regénérer package-lock.json pour que l'installation fonctionne, mais je n'ai pas mis à jour les dépendances dans ma branche puisque tu l'as fait.

**Comment by fuhrmanator** [comment]
fixed with #21
