### ISSUE TITLE
Exécuter les tests automatiquement et documenter la couverture de code

### ISSUE THREAD

**Issue by Olon11** [profcfuhrmanets/log210-systeme-gestion-bordereau-node-express-ts#3]
Lorsqu'on accède au dépôt GitHub, on ne sait pas si les tests passent et quelle est la couverture de code. Je suggère d'exécuter les tests à chaque commit/pull request et d'archiver la couverture de code dans un outil tel que Coveralls.

**Comment by fuhrmanator** [comment]
Pas prioritaire pour toi - je peux m'en occuper.

**Comment by fuhrmanator** [comment]
J'ai créé une action -- je ne pense pas que la couverture soit si importante pour l'instant. J'ajoute un badge facilement. En passant, dans le CI tu peux en créer:

![image](https://github.com/profcfuhrmanets/log210-systeme-gestion-bordereau-node-express-ts/assets/7606540/ffb05535-4318-473d-a273-d4cad346fbf9)

**Comment by Olon11** [comment]
J'ai ajouté la couverture et le badge dans mes changements.
