### ISSUE TITLE
Améliorer la gestion des erreurs

### ISSUE THREAD

**Issue by Olon11** [profcfuhrmanets/log210-systeme-gestion-bordereau-node-express-ts#5]
Les codes d'erreurs HTTP ne sont pas personnalisés au type d'erreur (ex.: 404 pour not found). S'inspirer de la gestion d'erreurs du squelette pour ajouter cet aspect au SGB.

**Comment by fuhrmanator** [comment]
As-tu un exemple concret où une erreur n'est pas bien transmise? C'est sûr que ça aidera à déboguer les implémentations du client.

**Comment by Olon11** [comment]
Par exemple, pour `login` dans `StudentRouter` et `TeacherRouter`, le code retourné est toujours 500. Ce code indique une erreur serveur (que c'est SGB qui a un bug), alors que ce n'est pas le cas.

**Comment by fuhrmanator** [comment]
> Je vais attendre la conversion des tests vers Jest avant de faire ce changement.

La conversion est terminée. Je suis d'accord avec l'amélioration des erreurs, surtout pour les raisons pédagogiques.
