### ISSUE TITLE
Remplacer Chai par Jest pour les tests

### ISSUE THREAD

**Issue by Olon11** [profcfuhrmanets/log210-systeme-gestion-bordereau-node-express-ts#7]
Voir le squelette pour faire le changement.

**Comment by fuhrmanator** [comment]
J'ai commencé le boulot déjà dans la fork nochai-migration https://github.com/profcfuhrmanets/log210-systeme-gestion-bordereau-node-express-ts/tree/nochai-migration

**Comment by fuhrmanator** [comment]
fixed with #21
