### ISSUE TITLE
Ajouter des validations pour le contenu inséré dans le SGB

### ISSUE THREAD

**Issue by Olon11** [profcfuhrmanets/log210-systeme-gestion-bordereau-node-express-ts#8]
Par exemple, lorsqu'on ajoute une note, ça n'a pas de sens d'avoir une note négative.

**Comment by fuhrmanator** [comment]
Je suis d'accord, mais il vaut mieux préciser les cas (comme la note négative).

**Comment by Olon11** [comment]
Si on veut seulement ajouter des validations au contenu inséré par les étudiants, il n'y a que la note négative.

Si on veut ajouter des validations au domaine en général (cours, enseignants, étudiants, etc.), il faudra vérifier que les champs sont non-vides. Pour moi, ce deuxième aspect est moins important que le premier, mais ça serait utile pour avoir un SGB blindé.
